version: '3.3'
services:
    neo4j:
        image: neo4j
        ports:
            - '7474:7474'
            - '7687:7687'
        environment:
            - NEO4J_AUTH=none
        volumes:
            - '$HOME/neo4j/data:/data'
