version: '3.3'
services:
  metabase:
    ports:
      - '3000:3000'
    container_name: metabase
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: host.docker.internal
