version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    network_mode: bridge
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password 
