version: '3.7'

services:
  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./hosts:/etc/hosts:ro # TODO: Some records might be emphemeral, I just copied the file from the state of the container then
      - ./www:/var/www:ro
    ports:
      - "80:80"
    restart: always
    network_mode: bridge # TODO: Not using this causes - Creating network "nginx_default" with the default driver
    # ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
